### PR TITLE
Add more parameters to config

### PR DESCRIPTION
**Pull request by phueper**
i needed some more parameters for my GCE instances:

- allow IP Forwarding
- specify fixed external IP
- specify disk_name to be used and wether to delete the disk after deleting the instance

I implemented these in this PR... the third point could be a partial fix for #15 i suppose.

### CODE REVIEW

**Comment by phueper** [comment]
oh... please excuse my ruby... this was the first time writing ruby for me... ;)

**Comment by Vad1mo** [comment]
+1

**Comment by sloppycoder** [comment]
+1

**Comment by erjohnso** [comment]
Looks great, thanks @phueper - sorry I missed this!

**Pull request merged**
