### PR TITLE
Add preemptible, auto_restart and on_host_maintenance

### PR DESCRIPTION
**Pull request by jcdang**
I added the variables under availability policy.

### CODE REVIEW

**Comment by Temikus** [comment]
@jcdang Thank you very much for doing this! \o/
Please, see to my comments above, otherwise - looks awesome!

I presume this will only work when https://github.com/fog/fog-google/pull/55 is released, correct?

**Comment by jcdang** [comment]
@Temikus That's right.

**Comment by Temikus** [comment]
@jcdang - Thank you! Tested, LGTM! :+1: 
Last thing - can you please squash commits before we pull this in? Should be as easy as `git rebase -i HEAD~4` from your branch and then marking the 3 latest commits with `s` and pushing with `--force`.

**Comment by jcdang** [comment]
@Temikus done sir

**Comment by Temikus** [comment]
Rebased changes on new master with 0.0.7. Looking good :+1: 

/CC @erjohnso 
LGTM! We can merge :fireworks:

**Comment by erjohnso** [comment]
Thanks @jcdang!  LGTM too!

**Pull request merged**
