### PR TITLE
Allow adding additional disks to GCE instance

### PR DESCRIPTION
**Pull request by whynick1**
Created `additional_disks` option that attach additional disks to GCE instance.
https://github.com/fog/fog-google/pull/434

### CODE REVIEW

**Comment by Temikus** [comment]
The image-family integration test is failing for some reason, need to debug this. I'll get back to you soon.

**Comment by criccomini** [comment]
@Temikus pinging--any update? :D

**Comment by Temikus** [comment]
@criccomini @whynick1 LGTM, merging.

Sorry for the additional wait, past couple of weeks  have been very hectic due to some life events. I'll release an RC version shortly after some small fixes.

**Comment by Temikus** [comment]
@criccomini @whynick1 Published the release candidate, you can test it out with `vagrant plugin install vagrant-google --plugin-version 2.3.0.rc0` If you have a chance, please take a look.

**Comment by whynick1** [comment]
Version 2.3.0.rc0 verified on our end! Thank you @Temikus

**Comment by Temikus** [comment]
Awesome! Thanks for checking @whynick1.

Merging.

**Comment by Temikus** [comment]
Released 2.3.0

**Pull request merged**
