### PR TITLE
resolve google key paths relative to Vagrantfile, not cwd

### LINKED ISSUE #159: Path to ssh key is resolved relative to cwd, not Vagrantfile
All the paths given in a `Vagrantfile` are resolved relative to the file itself, for example the ansible provisioners `ansible.playbook = "site.yml"`. This plugin always resolves the location of the SSH key relative to the current working directory. This breaks as soon as the user tries to execute a `vagrant`-command in a subdirectory.

Instead the plugin should look for the SSH key files relative to the `Vagrantfile`.

If you agree that this should be changed, I'll be more than happy to prepare a PR for it.

### PR DESCRIPTION
**Pull request by luto**
fixes #159

### CODE REVIEW

**Comment by Temikus** [comment]
LGTM! Thanks @luto 

@erjohnso - can you please merge?

**Comment by erjohnso** [comment]
Thanks for the contribution @luto!

And thanks for the review @Temikus

**Comment by luto** [comment]
Thanks for the merge!
@erjohnso is there a time frame of the next release?

**Comment by Temikus** [comment]
@luto Sorry for the late response.

So it looks like releasing a new version is not entirely trivial due to some dependency issues and the fact that bundler now disallows the hack that Vagrant uses to load up plugins in development.

I'll need some time to wrangle with it and do a prerelease.

I expect to address this sometime this/next week.

**Comment by Temikus** [comment]
@luto 1.0.0 released last week. Let me know if you have any questions.

**Comment by luto** [comment]
@Temikus Works great. Thanks!

**Pull request merged**
