### PR TITLE
Subnetwork support

### PR DESCRIPTION
**Pull request by Wyosotis**
Hello!

Please review this pull request for #164 issue.

### CODE REVIEW

**Comment by Wyosotis** [comment]
@Temikus could you please review this pull request? 
fog-google with subnetwork support [has been released](https://github.com/fog/fog-google/releases/tag/v0.5.3). 
Rake test results (with [this small fix](https://github.com/mitchellh/vagrant-google/pull/165)) are below: 
```
lkuntar@lkuntar-VirtualBox:~/workspace/forks/vagrant-google$ bundle exec rake
/usr/bin/ruby2.2 -S rspec test/unit/common/config_test.rb --color
.................................................................

Deprecation Warnings:

Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:33:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:34:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:35:in `block (2 levels) in <top (required)>'.
Too many uses of deprecated 'Use of rspec-core's `its` method'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:46:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

45 deprecation warnings total

Finished in 0.45853 seconds
65 examples, 0 failures
```

**Comment by Wyosotis** [comment]
Could someone review it please?
fog-google with subnetwork support [has been released](https://github.com/fog/fog-google/releases/tag/v0.5.3). 

Rake test results (with [this small fix](https://github.com/mitchellh/vagrant-google/pull/165)) are below: 
```
lkuntar@lkuntar-VirtualBox:~/workspace/forks/vagrant-google$ bundle exec rake
/usr/bin/ruby2.2 -S rspec test/unit/common/config_test.rb --color
.................................................................

Deprecation Warnings:

Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:33:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:34:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:35:in `block (2 levels) in <top (required)>'.
Too many uses of deprecated 'Use of rspec-core's `its` method'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /home/lkuntar/workspace/forks/vagrant-google/test/unit/common/config_test.rb:46:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

45 deprecation warnings total

Finished in 0.45853 seconds
65 examples, 0 failures
```

**Comment by erjohnso** [comment]
Thanks for this @Wyosotis - looks good to me!

**Comment by Wyosotis** [comment]
@erjohnso thank you for reviewing it. 
May I know when approximately a new release would appear? Because the new features that have been merged since last release (e.g. SSH over private IP), considerably improve experience with vagrant-google in real tasks.

**Comment by Temikus** [comment]
@Wyosotis So it looks like releasing a new version is not entirely trivial due to some dependency issues and the fact that bundler now disallows the hack that Vagrant uses to load up plugins in development.

I'll need some time to wrangle with it and do a prerelease.

I expect to address this sometime this/next week.

**Comment by Temikus** [comment]
@Wyosotis Ok, this is even less trivial than I thought, it actually interferes with plugin loading itself so I cannot even do a rollback without breaking recent versions of vagrant it seems.

I'll spend more time figuring this out this Friday, hopefully I'll be able to find a workaround which doesn't require a lot of rewriting.

**Pull request merged**
