### PR TITLE
Use GCE metadata service to grab the external IP

### PR DESCRIPTION
**Pull request by DazWilkin**

### CODE REVIEW

**Comment by erjohnso** [comment]
Thanks for this @DazWilkin!  This looks to be the same PR as #145. Perhaps you can close that one?

**Comment by erjohnso** [comment]
@Temikus, any concerns with this?

**Comment by DazWilkin** [comment]
@erjohnso killed #145 -- apologies for the dup.

**Comment by Temikus** [comment]
@erjohnso LGTM
Thanks @DazWilkin, that's neat! Didn't know one could query metadata like that.

**Comment by erjohnso** [comment]
Thanks again @DazWilkin, and thanks for the review @Temikus.

**Pull request merged**
