### PR TITLE
Cleanup created disk on failure

### PR DESCRIPTION
**Pull request by p0deje**
Related to #112

### CODE REVIEW

**Comment by p0deje** [comment]
Actually, there is another issue created now.

There is a case when Google responds with error (e.g. quote of IP addresses is exceeded), but still creates instance. In this case, trying to destroy disk raises exception:

```
Bringing machine 'default' up with 'google' provider...
==> default: Launching an instance with the following settings...
==> default:  -- Name:            example
==> default:  -- Type:            n1-standard-4
==> default:  -- Disk type:       pd-ssd
==> default:  -- Disk size:       15 GB
==> default:  -- Disk name:       
==> default:  -- Image:           coreos-1445053959
==> default:  -- Zone:            us-central1-b
==> default:  -- Network:         default
==> default:  -- Metadata:        '{}'
==> default:  -- Tags:            '[]'
==> default:  -- IP Forward:      
==> default:  -- External IP:     
==> default:  -- Preemptible:     true
==> default:  -- Auto Restart:    false
==> default:  -- On Maintenance:  TERMINATE
==> default:  -- Autodelete Disk: true
==> default:  -- Scopes:          ["storage-ro"]
/var/lib/jenkins/vagrant_home/gems/gems/fog-google-0.0.9/lib/fog/google.rb:232:in `build_excon_response': The disk resource 'example' is already being used by 'example' (Fog::Errors::Error)
```

What do you think if we also try to destroy instance (if it has actually been created) in this case and remove disk (if it was created by vagrant-google and autodelete disk is set to false)?

**Comment by Temikus** [comment]
@p0deje Thank you!  Tested this manually + integration tests. Looks alright.

If possible, can you also separate the cleanup into a method that gets takes (env) as the argument and squash the commits? This will allow me to reuse it later for user termination handling (sending SIGINT).

**Comment by p0deje** [comment]
@Temikus smth like this?

**Comment by Temikus** [comment]
@p0deje Yeah, one parameter seems to be a bit more complicated than I thought.

Let's mush it into one with something like this (need to be tested):
```
def cleanup(env, disk_name)
  zone = env[:machine].provider_config.zone
  zone_config = env[:machine].provider_config.get_zone_config(zone)
  autodelete_disk = zone_config.autodelete_disk
  if autodelete_disk && disk_name
    env[:google_compute].disks.get(disk_name, zone).destroy
  end
end
```
And if we don't need to delete the disk, just pass nil as the second value. What do you think?

**Comment by p0deje** [comment]
But in this approach we cannot use `disk_created_by_vagrant`?

**Comment by Temikus** [comment]
Just `cleanup(env, disk_name) if disk_created_by_vagrant`, or am I missing something?

**Comment by p0deje** [comment]
Hmm, but how is different to what we have now? I still need to check for `disk` before calling `disk.name`.

**Comment by Temikus** [comment]
Ah, sorry, I meant just having one `cleanup()` instead of `cleanup_disk()` and `cleanup_instance()`
I may be missing something though, do point it out if so.

**Comment by p0deje** [comment]
To create a single `cleanup` method, we'll have to share `disk_created_by_vagrant` as an instance variable or method argument. I think having separate method makes it more readable and obvious what's going on.

**Comment by Temikus** [comment]
You have a valid point, agreed. Let me run the test suite again and then looks good to merge.
Thanks @p0deje!

**Comment by Temikus** [comment]
LGTM, @erjohnso can you please merge?

**Comment by erjohnso** [comment]
LGTM too, thank you @p0deje and for the review/testing @Temikus!

**Comment by p0deje** [comment]
Thanks for merging!

Is there any chance you could do a minor release? For now I have to do some [hacking](https://github.com/p0deje/vagrant-google/commit/a3a5e92089aec9d1e3827c82f67c429ea8bec113) to install forked version on.

**Comment by Temikus** [comment]
@p0deje Sure. I'll prepare a release soon.

**Comment by Temikus** [comment]
@p0deje Released to RubyGems, master will be updated once #116 will be merged.
Let me know if you have any issues.

**Comment by erjohnso** [comment]
Thanks @p0deje and @Temikus - just merged #116 and tagged v0.2.0

**Pull request merged**
